### ISSUE TITLE
kpm模块加载失败

### ISSUE THREAD

**Issue by PaFuNya** [lzghzr/APatch_kpm#9]
[APatch_bugreport_2024-08-27_14_30.tar.gz](https://github.com/user-attachments/files/16757633/APatch_bugreport_2024-08-27_14_30.tar.gz)
--------- beginning of crash
08-27 14:10:34.334 12171 12171 F libc : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12171 (main), pid 12171 (main)
08-27 14:10:34.577 12175 12175 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-27 14:10:34.577 12175 12175 F DEBUG : RisingOS Version: '3.2'
08-27 14:10:34.577 12175 12175 F DEBUG : Build fingerprint: 'google/rising_arm64_bcgN/arm64_bcgN:14/AP1A.240505.005/eng.nobody.20240602.143639:user/release-keys'
08-27 14:10:34.577 12175 12175 F DEBUG : Revision: '0'
08-27 14:10:34.577 12175 12175 F DEBUG : ABI: 'arm64'
08-27 14:10:34.577 12175 12175 F DEBUG : Timestamp: 2024-08-27 14:10:34.387572561+0800
08-27 14:10:34.577 12175 12175 F DEBUG : Process uptime: 2s
08-27 14:10:34.577 12175 12175 F DEBUG : Cmdline: me.bmax.apatch:root:0
08-27 14:10:34.577 12175 12175 F DEBUG : pid: 12171, tid: 12171, name: main >>> me.bmax.apatch:root:0 
08-27 14:10:34.577 12175 12175 F DEBUG : uid: 10586
08-27 14:10:34.577 12175 12175 F DEBUG : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
08-27 14:10:34.577 12175 12175 F DEBUG : Abort message: 'Check failed: system_class_loader != nullptr java.lang.ExceptionInInitializerError: 
08-27 14:10:34.577 12175 12175 F DEBUG : at java.lang.ClassLoader java.lang.ClassLoader.getSystemClassLoader() (ClassLoader.java:1907)
08-27 14:10:34.577 12175 12175 F DEBUG : Caused by: java.lang.SecurityException: Writable dex file '/data/user_de/0/me.bmax.apatch/cache/main.jar' is not allowed.
08-27 14:10:34.577 12175 12175 F DEBUG : at java.lang.Object dalvik.system.DexFile.openDexFileNative(java.lang.String, java.lang.String, int, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:-2)
08-27 14:10:34.577 12175 12175 F DEBUG : at java.lang.Object dalvik.system.DexFile.openDexFile(java.lang.String, java.lang.String, int, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:406)
08-27 14:10:34.577 12175 12175 F DEBUG : at void dalvik.system.DexFile.(java.lang.String, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:128)
08-27 14:10:34.577 12175 12175 F DEBUG : at void dalvik.system.DexFile.(java.io.File, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexFile.java:101)
08-27 14:10:34.577 12175 12175 F DEBUG : at dalvik.system.DexFile dalvik.system.DexPathList.loadDexFile(java.io.File, java.io.File, java.lang.ClassLoader, dalvik.system.DexPathList$Element[]) (DexPathList.java:438)
08-27 14:10:34.577 12175 12175 F DEBUG : at dalvik.system.DexPathList$Element[] dalvik.system.DexPathList.makeDexElements(java.util.List, java.io.File, java.util.List, java.lang.ClassLoader, boolean) (DexPathList.java:397)
08-27 14:10:34.577 12175 12175 F DEBUG : at void dalvik.system.DexPathList.(java.lang.ClassLoader, java.lang.String, java.lang.String, java.io.File, boolean) (DexPathList.java:166)
08-27 14:10:34.577 12175 12175 F DEBUG : at void dalvik.system.BaseDexClassLoader.(java.lang.String, java.lang.String, java.lang.ClassLoader, java.lang.ClassLoader[], java.lang.ClassLoader[], boolean) (BaseDexClassLoader.java:160)
08-27 14:10:34.577 12175 12175 F DEBUG : at void dalvik.system.BaseDexClassLoader.(java.lang.String, java.io.File, java.lang.String, java.lang.ClassLoader) (BaseDexClassLoader.java:105)
08-27 14:10:34.577 12175 12175 F DEBUG : at void dalvik.system.PathClassLoader.(java.lang.String, java.lang.String, java.lang.ClassLoader) (PathClassLoader.java:71)
08-27 14:10:34.577 12175 12175 F DEBUG : at java.lang.ClassLoader java.lang.ClassLoader.createSystemClassLoader() (ClassLoader.java:267)
08-27 14:10:34.577 12175 12175 F DEBUG : at java.lang.ClassLoader java.lang.ClassLoader.-$$Nest$smcreateSystemClassLoader() (ClassLoader.java:-1)
08-27 14:10:34.577 12175 12175 F DEBUG : at void java.lang.ClassLoader$SystemClassLoader.() (ClassLoader.java:217)
08-27 14:10:34.577 12175 12175 F DEBUG : at java.lang.ClassLoader java.lang.ClassLoader.getSystemClassLoader() (ClassLoader.java:1907)'
08-27 14:10:34.578 12175 12175 F DEBUG : x0 0000000000000000 x1 0000000000002f8b x2 0000000000000006 x3 0000007fc2bdc6a0
08-27 14:10:34.578 12175 12175 F DEBUG : x4 0000007d8e769000 x5 0000007d8e769000 x6 0000007d8e769000 x7 0000000000006184
08-27 14:10:34.578 12175 12175 F DEBUG : x8 00000000000000f0 x9 0000007d6246a400 x10 0000000000000001 x11 0000007d624bd400
08-27 14:10:34.578 12175 12175 F DEBUG : x12 0000007fc2bdb420 x13 0000000000000a21 x14 0000007fc2bdb4d0 x15 0000420dca3f93c7
08-27 14:10:34.578 12175 12175 F DEBUG : x16 0000007d62529fd8 x17 0000007d624fff80 x18 0000007d8e1b0000 x19 0000000000002f8b
08-27 14:10:34.578 12175 12175 F DEBUG : x20 0000000000002f8b x21 00000000ffffffff x22 0000007ac59c6000 x23 0000000000000016
08-27 14:10:34.578 12175 12175 F DEBUG : x24 0000007d8d46bc00 x25 0000007d8cbf52b0 x26 0000007ac59c6000 x27 b400007c66611ab8
08-27 14:10:34.578 12175 12175 F DEBUG : x28 0000007fc2bddc70 x29 0000007fc2bdc720
08-27 14:10:34.578 12175 12175 F DEBUG : lr 0000007d624af2ec sp 0000007fc2bdc680 pc 0000007d624af318 pst 0000000000000000
08-27 14:10:34.578 12175 12175 F DEBUG : 12 total frames
08-27 14:10:34.578 12175 12175 F DEBUG : backtrace:
08-27 14:10:34.578 12175 12175 F DEBUG : #00 pc 0000000000068318 /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 8a199c85eb786c47b29919b38cf88684)
08-27 14:10:34.578 12175 12175 F DEBUG : #01 pc 000000000091a1a8 /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+528) (BuildId: 3a0499bbf274a88a639802f270ec45c5)
08-27 14:10:34.578 12175 12175 F DEBUG : #02 pc 00000000000251d8 /apex/com.android.art/lib64/libbase.so (android::base::SetAborter(std::__1::function&&)::$_0::__invoke(char const*)+80) (BuildId: 48e84ff7f2fc6e9c383132b16756577e)
08-27 14:10:34.578 12175 12175 F DEBUG : #03 pc 0000000000024760 /apex/com.android.art/lib64/libbase.so (android::base::LogMessage::~LogMessage()+352) (BuildId: 48e84ff7f2fc6e9c383132b16756577e)
08-27 14:10:34.578 12175 12175 F DEBUG : #04 pc 00000000005bde8c /apex/com.android.art/lib64/libart.so (art::CreateSystemClassLoader(art::Runtime*) (.__uniq.123643984379049060189133697593660836796)+1220) (BuildId: 3a0499bbf274a88a639802f270ec45c5)
08-27 14:10:34.578 12175 12175 F DEBUG : #05 pc 00000000005b6430 /apex/com.android.art/lib64/libart.so (art::Runtime::Start()+508) (BuildId: 3a0499bbf274a88a639802f270ec45c5)
08-27 14:10:34.578 12175 12175 F DEBUG : #06 pc 00000000005b5fb8 /apex/com.android.art/lib64/libart.so (JNI_CreateJavaVM+308) (BuildId: 3a0499bbf274a88a639802f270ec45c5)
08-27 14:10:34.578 12175 12175 F DEBUG : #07 pc 00000000002102d8 /system/lib64/libandroid_runtime.so (JNI_CreateJavaVM+68) (BuildId: 2e9b017168b3237b74bdf37aae4ec906)
08-27 14:10:34.578 12175 12175 F DEBUG : #08 pc 00000000000e5b38 /system/lib64/libandroid_runtime.so (android::AndroidRuntime::startVm(_JavaVM**, _JNIEnv**, bool, bool)+9540) (BuildId: 2e9b017168b3237b74bdf37aae4ec906)
08-27 14:10:34.578 12175 12175 F DEBUG : #09 pc 00000000000e6180 /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector const&, bool)+464) (BuildId: 2e9b017168b3237b74bdf37aae4ec906)
08-27 14:10:34.578 12175 12175 F DEBUG : #10 pc 0000000000010580 /system/bin/app_process64 (main+1224) (BuildId: 5c44ff65d1938d47c319c9e3ea57d177)
08-27 14:10:34.578 12175 12175 F DEBUG : #11 pc 0000000000060634 /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 8a199c85eb786c47b29919b38cf88684)
08-27 14:10:47.696 12422 12422 F libc : Fatal signal 31 (SIGSYS), code 1 (SYS_SECCOMP), syscall 116 in tid 12422 (dmesg), pid 12422 (dmesg)
08-27 14:10:47.720 12425 12425 F DEBUG : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-27 14:10:47.720 12425 12425 F DEBUG : RisingOS Version: '3.2'
08-27 14:10:47.720 12425 12425 F DEBUG : Build fingerprint: 'google/rising_arm64_bcgN/arm64_bcgN:14/AP1A.240505.005/eng.nobody.20240602.143639:user/release-keys'
08-27 14:10:47.720 12425 12425 F DEBUG : Revision: '0'
08-27 14:10:47.720 12425 12425 F DEBUG : ABI: 'arm64'
08-27 14:10:47.720 12425 12425 F DEBUG : Timestamp: 2024-08-27 14:10:47.709506514+0800
08-27 14:10:47.720 12425 12425 F DEBUG : Process uptime: 1s
08-27 14:10:47.720 12425 12425 F DEBUG : Cmdline: dmesg
08-27 14:10:47.720 12425 12425 F DEBUG : pid: 12422, tid: 12422, name: dmesg >>> dmesg 
08-27 14:10:47.720 12425 12425 F DEBUG : uid: 10586
08-27 14:10:47.720 12425 12425 F DEBUG : signal 31 (SIGSYS), code 1 (SYS_SECCOMP), fault addr --------
08-27 14:10:47.720 12425 12425 F DEBUG : Cause: seccomp prevented call to disallowed arm64 system call 116
08-27 14:10:47.720 12425 12425 F DEBUG : x0 000000000000000a x1 0000000000000000 x2 0000000000000000 x3 0000000000000000
08-27 14:10:47.720 12425 12425 F DEBUG : x4 0000007fede78331 x5 0000000000000004 x6 00000080260c0daf x7 4145006365440038
08-27 14:10:47.720 12425 12425 F DEBUG : x8 0000000000000074 x9 f60b730b5ad59cd3 x10 0000007fede76290 x11 0000007fede76260
08-27 14:10:47.720 12425 12425 F DEBUG : x12 ffffff80ffffffd0 x13 0000000000000040 x14 0000000000000040 x15 ffffffffffffffff
08-27 14:10:47.720 12425 12425 F DEBUG : x16 0000005efc12c210 x17 0000007b7530ccc0 x18 0000007b7df90000 x19 0000000000000000
08-27 14:10:47.720 12425 12425 F DEBUG : x20 0000000000000000 x21 0000007b7d6d9fc0 x22 0000005efc13e000 x23 0000005efc13e000
08-27 14:10:47.720 12425 12425 F DEBUG : x24 0000005efc13c450 x25 0000000000000000 x26 0000000000000000 x27 0000000000000000
08-27 14:10:47.720 12425 12425 F DEBUG : x28 0000000000000000 x29 0000007fede78340
08-27 14:10:47.720 12425 12425 F DEBUG : lr 0000005efc10412c sp 0000007fede76330 pc 0000007b7530ccc8 pst 0000000060000000
08-27 14:10:47.720 12425 12425 F DEBUG : 6 total frames
08-27 14:10:47.720 12425 12425 F DEBUG : backtrace:
08-27 14:10:47.721 12425 12425 F DEBUG : #00 pc 00000000000bbcc8 /apex/com.android.runtime/lib64/bionic/libc.so (klogctl+8) (BuildId: 8a199c85eb786c47b29919b38cf88684)
08-27 14:10:47.721 12425 12425 F DEBUG : #01 pc 000000000005c128 /system/bin/toybox (dmesg_main+432) (BuildId: 0a9c0790f7b21ed864bd8daa4ea7bbc7)
08-27 14:10:47.721 12425 12425 F DEBUG : #02 pc 0000000000039a10 /system/bin/toybox (toy_exec_which+164) (BuildId: 0a9c0790f7b21ed864bd8daa4ea7bbc7)
08-27 14:10:47.721 12425 12425 F DEBUG : #03 pc 0000000000039260 /system/bin/toybox (toybox_main+128) (BuildId: 0a9c0790f7b21ed864bd8daa4ea7bbc7)
08-27 14:10:47.721 12425 12425 F DEBUG : #04 pc 0000000000039a88 /system/bin/toybox (main+112) (BuildId: 0a9c0790f7b21ed864bd8daa4ea7bbc7)
08-27 14:10:47.721 12425 12425 F DEBUG : #05 pc 0000000000060634 /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+104) (BuildId: 8a199c85eb786c47b29919b38cf88684)
--------- beginning of main
08-27 14:18:02.291 12035 12035 W me.bmax.apatch: Accessing hidden field Landroid/view/inputmethod/InputMethodManager;->mCurRootView:Landroid/view/ViewRootImpl; (blocked, reflection, denied)
08-27 14:18:02.292 12035 12035 W me.bmax.apatch: Accessing hidden field Landroid/view/inputmethod/InputMethodManager;->mServedView:Landroid/view/View; (blocked, reflection, denied)
08-27 14:18:02.292 12035 12035 W me.bmax.apatch: Accessing hidden field Landroid/view/inputmethod/InputMethodManager;->mNextServedView:Landroid/view/View; (blocked, reflection, denied)
08-27 14:18:02.292 12035 12035 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@7c5f853
08-27 14:18:05.718 12035 12076 D KPModuleViewModel: kpm list: []
08-27 14:18:05.719 12035 12076 I KPModuleViewModel: load cost: 0, modules: []
08-27 14:18:06.989 16706 16706 W libkpatch.so: type=1400 audit(0.0:3787): avc: denied { search } for name="tests" dev="sda19" ino=111 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=me.bmax.apatch
08-27 14:18:06.989 16706 16706 W libkpatch.so: type=1400 audit(0.0:3788): avc: denied { search } for name="tests" dev="sda19" ino=111 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=me.bmax.apatch
08-27 14:18:06.989 16706 16706 W libkpatch.so: type=1400 audit(0.0:3789): avc: denied { search } for name="tests" dev="sda19" ino=111 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=me.bmax.apatch
08-27 14:18:06.989 16706 16706 W libkpatch.so: type=1400 audit(0.0:3790): avc: denied { search } for name="tests" dev="sda19" ino=111 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=me.bmax.apatch
08-27 14:18:06.998 12035 12035 E APatchCli: su failed: 
08-27 14:18:06.998 12035 12035 E APatchCli: WJ: Unable to create a shell!
08-27 14:18:06.998 12035 12035 E APatchCli: 	at Y2.g(Unknown Source:58)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at Y2.h(Unknown Source:13)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at U60.E(Unknown Source:67)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at rN.(Unknown Source:151)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at mu.b(Unknown Source:12)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at r90.c(Unknown Source:111)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at r90.b(Unknown Source:4)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at r90.a(Unknown Source:4)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eV.a(Unknown Source:65)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at w2.n(Unknown Source:50)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at w2.m(Unknown Source:12)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at kA.X(Unknown Source:75)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at tB.a(Unknown Source:150)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at YM.e(Unknown Source:49)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at wF.u(Unknown Source:46)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at bm.g(Unknown Source:183)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.b(Unknown Source:38)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.g(Unknown Source:8)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at u.l(Unknown Source:614)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.l(Unknown Source:46)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at F6.s(Unknown Source:4)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eG.f(Unknown Source:202)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at RU.c(Unknown Source:93)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at vB.g(Unknown Source:57)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at CI.l(Unknown Source:66)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.l(Unknown Source:46)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at F6.s(Unknown Source:4)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eG.g(Unknown Source:137)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at vB.b(Unknown Source:43)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at VI.g(Unknown Source:71)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.b(Unknown Source:38)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.g(Unknown Source:8)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at f6.k(Unknown Source:3092)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.a(Unknown Source:38)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.k(Unknown Source:8)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at androidx.compose.animation.a.a(Unknown Source:1322)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at g6.l(Unknown Source:270)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eg.l(Unknown Source:46)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at eG.b(Unknown Source:1007)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at gB.c(Unknown Source:1894)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at XI.l(Unknown Source:119)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at dh.G(Unknown Source:477)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at dh.N(Unknown Source:57)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at dh.r(Unknown Source:169)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at dh.E(Unknown Source:28)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at hh.v(Unknown Source:34)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at GR.p(Unknown Source:109)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at IA.m(Unknown Source:443)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at B5.doFrame(Unknown Source:6)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at z5.doFrame(Unknown Source:47)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1397)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.view.Choreographer.doFrame(Choreographer.java:934)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.os.Handler.handleCallback(Handler.java:959)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.os.Looper.loopOnce(Looper.java:232)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.os.Looper.loop(Looper.java:317)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at android.app.ActivityThread.main(ActivityThread.java:8527)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
08-27 14:18:06.998 12035 12035 E APatchCli: Caused by: java.io.IOException: Created process is not a shell
08-27 14:18:06.998 12035 12035 E APatchCli: 	at Zz.call(Unknown Source:172)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at oX.call(Unknown Source:19)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
08-27 14:18:06.998 12035 12035 E APatchCli: 	at java.lang.Thread.run(Thread.java:1012)
08-27 14:18:07.018 12035 12035 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
08-27 14:18:07.018 12035 12035 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
08-27 14:18:07.019 16710 16710 W kptools : type=1400 audit(0.0:3791): avc: denied { search } for name="tests" dev="sda19" ino=111 scontext=u:r:untrusted_app:s0:c74,c258,c512,c768 tcontext=u:object_r:shell_test_data_file:s0 tclass=dir permissive=0 app=me.bmax.apatch
08-27 14:18:07.110 12035 12035 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda11@38136f9
08-27 14:18:07.111 12035 12057 D HWUI : endAllActiveAnimators on 0xb400007abe32d300 (D70) with handle 0xb400007a4e310df0
08-27 14:18:08.598 12035 12035 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
08-27 14:18:08.598 12035 12035 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
08-27 14:18:11.767 12035 12

**Comment by Whiteispure** [comment]
[APatch_bugreport_2024-08-27_14_53.tar.gz](https://github.com/user-attachments/files/16757903/APatch_bugreport_2024-08-27_14_53.tar.gz)

**Comment by lzghzr** [comment]
加载debug版再发日志
https://github.com/lzghzr/APatch_kpm/releases/tag/1.0.0

**Comment by Whiteispure** [comment]
> 加载debug版再发日志
> https://github.com/lzghzr/APatch_kpm/releases/tag/1.0.0


![APatch_bugreport_2024-08-27_15_11.tar.gz](https://github.com/user-attachments/files/16758088/APatch_bugreport_2024-08-27_15_11.tar.gz)

**Comment by Whiteispure** [comment]
![APatch_bugreport_2024-08-27_15_11.tar.gz](https://github.com/user-attachments/files/16758099/APatch_bugreport_2024-08-27_15_11.tar.gz)

> 加载debug版再发日志
> https://github.com/lzghzr/APatch_kpm/releases/tag/1.0.0

**Comment by lzghzr** [comment]
看了一眼，你可以用6.0.9这个版本

**Comment by Whiteispure** [comment]
加载是成功加载了，但是嵌入不了模块，而且加载成功之后再次打开apatch就会卡屏进不去，得把他清空存储空间和缓存才能进去，但是这样模块又全部消失了而且得重新输入超级密钥，我是不是该换一个apatch试试，或者说不要用面具了？难整哦

**Comment by lzghzr** [comment]
> 加载是成功加载了，但是嵌入不了模块，而且加载成功之后再次打开apatch就会卡屏进不去，得把他清空存储空间和缓存才能进去，但是这样模块又全部消失了而且得重新输入超级密钥，我是不是该换一个apatch试试，或者说不要用面具了？难整哦

试试这个，看了下你的内核还挺特殊的
[re_kernel_6.0.10_debug.kpm.gz](https://github.com/user-attachments/files/16784003/re_kernel_6.0.10_debug.kpm.gz)

**Comment by Whiteispure** [comment]
> > 加载是成功加载了，但是嵌入不了模块，而且加载成功之后再次打开apatch就会卡屏进不去，得把他清空存储空间和缓存才能进去，但是这样模块又全部消失了而且得重新输入超级密钥，我是不是该换一个apatch试试，或者说不要用面具了？难整哦
> 
> 试试这个，看了下你的内核还挺特殊的
> [re_kernel_6.0.10_debug.kpm.gz](https://github.com/user-attachments/files/16784003/re_kernel_6.0.10_debug.kpm.gz)
> 

谢谢哥，已经放弃了，就用kill得了。感谢❤️❤️
